name: Finora
options:
  bundleIdPrefix: com.finora
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  Finora:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: .
        excludes:
          - "Tests/**"
          - "*.md"
          - "*.txt"
          - "*.yml"
          - "project.yml"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finora.app
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      TARGETED_DEVICE_FAMILY: "1,2"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited)"
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Finora
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UIApplicationSupportsIndirectInputEvents: true
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  FinoraTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Tests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finora.tests
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Finora.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Finora"
    dependencies:
      - target: Finora
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: BNDL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"

schemes:
  Finora:
    build:
      targets:
        Finora: all
    test:
      targets:
        - FinoraTests
    run:
      config: Debug
    archive:
      config: Release

