name: Finora
options:
  bundleIdPrefix: com.finora
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"
  PRODUCT_NAME: "Finora"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  TARGETED_DEVICE_FAMILY: "1,2"
  SUPPORTS_MACCATALYST: false
  GENERATE_INFOPLIST_FILE: true
  INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
  INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
  INFOPLIST_KEY_UILaunchScreen_Generation: true
  INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  ENABLE_PREVIEWS: true
  ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

targets:
  Finora:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Finora
    resources:
      - Finora/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.finora.app
        INFOPLIST_KEY_CFBundleDisplayName: "Finora"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    scheme:
      testTargets:
        - FinoraTests
      gatherCoverageData: true

  FinoraTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - FinoraTests
    dependencies:
      - target: Finora
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.finora.app.tests
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""

schemes:
  Finora:
    build:
      targets:
        Finora: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - FinoraTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
